### ISSUE TITLE
Extract strings from source code with xgettext

### ISSUE THREAD

**Issue by armijnhemel** [nexB/source-inspector#3] opened 2024-01-29 14:57 UTC
Some notes for extracting strings from source code files with `xgettext`.

I have found the following commandline options to work well for me:

```
xgettext -a -o - --no-wrap --no-location --omit-header -
```

This reads the data from standard input, and outputs results on standard output. The standard gettext header is not included (which makes parsing a little bit easier) and file name data is also not included (the "location"), as I am assuming I already know which file I am reading plus I am not interested in the location(s) of the strings in the file (but maybe this is something you want). This also makes parsing things a little bit easier. The `--no-wrap` parameter is for putting results on a single line, which also makes processing results easier.

Some options that are worth looking at: `-L` as `xgettext` tends to only look at file extensions.

**Comment by pombredanne** [comment] 2024-03-15 07:55
Closing https://github.com/nexB/source-inspector/issues/3 as dupe of this

**Comment by pombredanne** [comment] 2024-03-15 09:24
This is now completed with PR #7
To test this feature:
- pip install source-inspector
- scancode --source-string --yaml - <path to some source file>

You will see the "source_strings" data attached to a each source file entry

**Closed** 2024-04-03 11:32 UTC
